"""
secure_store.py — Authenticated encryption for sensitive values stored in the database.

Protects data that must not be readable if ONLY the database is stolen or misconfigured (a cloud Supabase project,
a copied forensic.db): face embeddings (biometric templates) and the two-factor secret. The key lives outside the
database: SIH_DATA_KEY (urlsafe base64, 32 bytes) or a key file created on first use in SIH_KEY_DIR
(default ~/.sih_forensic/data.key).

Values are stored as "enc1:<fernet token>" (AES-128-CBC + HMAC-SHA256, via the `cryptography` package). Values
written before this existed (no prefix) are still read, and are re-encrypted the next time they are saved.

Limit: anyone holding the key AND the database can read the values. Back the key up: without it the encrypted
values are unrecoverable (embeddings can be regenerated by re-running face detection; the 2FA secret cannot,
see docs for the recovery procedure).
"""

from __future__ import annotations

import os
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

PREFIX = "enc1:"


def key_dir() -> Path:
    base = os.environ.get("SIH_KEY_DIR", "").strip()
    return Path(base) if base else Path.home() / ".sih_forensic"


def _fernet() -> Fernet:
    env = os.environ.get("SIH_DATA_KEY", "").strip()
    if env:
        return Fernet(env.encode("ascii"))
    kf = key_dir() / "data.key"
    if kf.is_file():
        return Fernet(kf.read_bytes().strip())
    kf.parent.mkdir(parents=True, exist_ok=True)
    key = Fernet.generate_key()
    kf.write_bytes(key)
    try:
        os.chmod(kf, 0o600)
    except OSError:
        pass
    return Fernet(key)


def encrypt_text(plain: str) -> str:
    return PREFIX + _fernet().encrypt(plain.encode("utf-8")).decode("ascii")


def is_encrypted(value: str) -> bool:
    return value.startswith(PREFIX)


def decrypt_text(value: str) -> str:
    """Decrypt an 'enc1:' value; pass legacy plaintext through unchanged. Raises ValueError on a bad key/token."""
    if not is_encrypted(value):
        return value
    try:
        return _fernet().decrypt(value[len(PREFIX):].encode("ascii")).decode("utf-8")
    except InvalidToken as exc:
        raise ValueError("Encrypted value cannot be decrypted (wrong or missing key, or the data was altered).") from exc
