"""The test-pack generator (tools/make_test_pack.py): builds the images, and what the tool then finds in them matches
what was put in. Uses the short 4-second version so it stays quick."""

import shutil
import sys
from pathlib import Path

import pytest

from backend.exporter import ffmpeg_available, ffprobe_available

pytestmark = pytest.mark.skipif(not (ffmpeg_available() and ffprobe_available()), reason="ffmpeg/ffprobe not on PATH")

TOOLS = Path(__file__).resolve().parents[2] / "tools"


@pytest.fixture(scope="module")
def pack(tmp_path_factory):
    sys.path.insert(0, str(TOOLS))
    try:
        import make_test_pack
    finally:
        sys.path.remove(str(TOOLS))
    out = tmp_path_factory.mktemp("pack")
    info = make_test_pack.build(out, 4, None, None, verify_pack=True)
    yield out, info
    shutil.rmtree(out, ignore_errors=True)


def test_all_the_files_are_written(pack):
    out, _ = pack
    for rel in ("people/person_A.png", "people/person_B.png", "truth_videos/camera1_persons_A_and_B.mp4",
                "truth_videos/camera2_person_B_only.mp4", "disks/dahua_before_deletion.dd", "disks/dahua_deleted.dd",
                "disks/dahua_partly_overwritten.dd", "disks/dahua_deleted_stress_tiny_clusters.dd",
                "disks/cpplus_deleted.dd", "disks/tplink_deleted.dd", "START_HERE.md", "expected_results.json"):
        assert (out / rel).is_file() and (out / rel).stat().st_size > 0, rel


def test_the_two_people_are_told_apart_by_the_tools_own_face_model(pack):
    from backend import face_search
    _, info = pack
    assert info["similarities"]["A-B"] < face_search.REFERENCE_MATCH_THRESHOLD - 0.15


def test_brands_are_reported_the_way_the_guide_says(pack):
    _, info = pack
    seen = info["observed"]
    assert seen["dahua_deleted.dd"]["brand"] == "Dahua" and seen["dahua_deleted.dd"]["confidence"] == 1.0
    assert "CP Plus" in seen["cpplus_deleted.dd"]["brand"] and "unverified" in seen["cpplus_deleted.dd"]["brand"]
    assert seen["tplink_deleted.dd"]["generic"] is True and "TP-Link" in seen["tplink_deleted.dd"]["brand"]


def test_deleted_dahua_video_is_recovered_decodes_and_shows_both_people(pack):
    _, info = pack
    segs = info["observed"]["dahua_deleted.dd"]["segments"]
    assert len(segs) == 2 and all(s["decodes"] for s in segs)
    assert max(s["faces_max_in_frame"] for s in segs) == 2          # camera 1 has two people on screen at once
    assert all(s["status"] == "PARTIAL" for s in segs)              # carving alone is never "complete"


def test_face_search_finds_the_right_person_in_the_right_camera(pack):
    from backend import face_search
    _, info = pack
    thr = face_search.REFERENCE_MATCH_THRESHOLD
    cam1, cam2 = sorted(info["observed"]["dahua_deleted.dd"]["segments"], key=lambda s: s["start"])
    assert cam1["best_similarity"]["A"] > thr and cam1["best_similarity"]["B"] > thr      # both are in camera 1
    assert cam2["best_similarity"]["B"] > thr and cam2["best_similarity"]["A"] < thr      # only B is in camera 2


def test_tplink_has_no_times_and_is_one_generic_segment(pack):
    _, info = pack
    segs = info["observed"]["tplink_deleted.dd"]["segments"]
    assert len(segs) == 1 and segs[0]["start"] == "None"


def test_stress_image_looks_recovered_but_the_accuracy_check_exposes_it(pack):
    _, info = pack
    from testpack import verify  # noqa: F401  (imported by the fixture's sys.path)
    acc = __import__("json").loads((pack[0] / "expected_results.json").read_text())["_accuracy"]
    assert acc["deleted_vs_camera1_clip"]["frame_recall"] > 80
    assert acc["stress_vs_camera1_clip"]["frame_recall"] < acc["deleted_vs_camera1_clip"]["frame_recall"] / 2


def test_the_guide_quotes_the_measured_numbers(pack):
    out, _ = pack
    text = (out / "START_HERE.md").read_text(encoding="utf-8")
    assert "generated by our own script" in text and "not real people" in text
    assert "measured by running the tool on this exact pack" in text
