"""guide.py — write START_HERE.md and expected_results.json for a finished pack, from the numbers verify.py observed."""

from __future__ import annotations

import json
from pathlib import Path


def _seg_lines(v: dict) -> str:
    rows = []
    for s in v["segments"]:
        faces = "-" if s["faces_max_in_frame"] is None else str(s["faces_max_in_frame"])
        sim = s["best_similarity"]
        a = "-" if sim.get("A") is None else f"{sim['A']:.2f}"
        b = "-" if sim.get("B") is None else f"{sim['B']:.2f}"
        times = f"{s['start'][11:19]} - {s['end'][11:19]}" if s["start"] != "None" else "no times"
        rows.append(f"| {s['camera']} | {s['frames']} | {times} | {'yes' if s['decodes'] else 'no'} | {faces} | {a} | {b} |")
    head = "| Camera | Frames | Recorder time | Video plays | Most faces in one frame | Similarity to person A | to person B |\n|---|---:|---|---|---:|---:|---:|\n"
    return head + "\n".join(rows)


def write(out: Path, r: dict, seconds: int, sims: dict, own_photos: bool) -> None:
    thr = r["_threshold"]
    segs = r["dahua_deleted.dd"]["segments"]
    t0, t1 = min(x["start"] for x in segs)[11:19], max(x["end"] for x in segs)[11:19]
    import re as _re
    m = _re.search(r"(\d+) frame\(s\) that straddled", r['dahua_deleted_stress_tiny_clusters.dd']['carve_note'])
    stitched = m.group(1) if m else '0'
    acc = r["_accuracy"]
    people_note = ("Persons A and B are **your own photos**." if own_photos else
                   "Persons A and B are **cartoon avatars drawn by the generator** (not real people, not photographs).")
    text = f"""# Test pack: START HERE

Everything in this folder was **generated by our own script** ({seconds}-second videos). No physical recorder wrote any of it.
{people_note} It proves that the tool's steps work and that its results match what we put in. It does **not** prove that a real
recorder's disk will decode: that needs a real disk and the Validation Kit.

## What is in the folder

| Folder / file | What it is |
|---|---|
| `people/person_A.png`, `person_B.png` | The two people in the videos. Use them as **reference photos** for face search. |
| `truth_videos/camera1_persons_A_and_B.mp4` | The original Camera 1 video: **A and B both on screen** (they walk in, stand side by side, then leave). |
| `truth_videos/camera2_person_B_only.mp4` | The original Camera 2 video: only **B**, walking across. Starts 3 seconds after Camera 1, so the two overlap in time. |
| `disks/dahua_before_deletion.dd` | A Dahua-style disk with both recordings **intact**. |
| `disks/dahua_deleted.dd` | The same disk after the recordings were **deleted** (the index wiped, the video bytes left behind). |
| `disks/dahua_partly_overwritten.dd` | Deleted, and part of the footage then **overwritten** by other data. |
| `disks/dahua_deleted_stress_tiny_clusters.dd` | A deliberately hard case (see test 6). |
| `disks/cpplus_deleted.dd` | A CP Plus-style disk (Dahua-compatible layout is an **assumption**) with the video left on it. |
| `disks/tplink_deleted.dd` | A TP-Link-style disk. The tool has **no TP-Link parser**, so this shows the generic fallback. |

## How to load a disk

Open the tool, **New Case**, then **Add disk image**. Either drop the `.dd` file on the upload area, or type its path under
Option 2. Then open **Acquisition & Scan** and press **Start Carving Scan**. When it finishes, press **View recordings**.

Leave the "device clock offset" box empty: the times then show exactly as read from the disk (the tool never guesses a time zone).

## What you should see (measured by running the tool on this exact pack)

### Test 1: Dahua, deleted (`dahua_deleted.dd`): the main test
Brand **{r['dahua_deleted.dd']['brand']}**, confidence {r['dahua_deleted.dd']['confidence']}. The index says it holds **0 recordings** (deleted),
so everything comes from carving the leftover video.

{_seg_lines(r['dahua_deleted.dd'])}

- Both recordings come back, every one labelled **PARTIAL** (never COMPLETE: carving alone cannot prove completeness).
- The Camera 1 recording is shown as **Camera 0** and Camera 2 as **Camera 1**: carved Dahua frames report the channel number stored in the
  frame, which this pack numbers from 0. (The intact disk in test 2 shows 1 and 2, because the index numbers them from 1.)
- Press **Export** on each, then **Play**: you should see the room with the two people.

### Test 2: Dahua, intact (`dahua_before_deletion.dd`)
Read straight from the recorder's own index: Cameras 1 and 2. The **Frames** column shows a small number (for example {r['dahua_before_deletion.dd']['segments'][0]['frames']}):
for an index read it counts recording *pieces*, not video frames. Faces and similarity match test 1.

### Test 3: Dahua, partly overwritten (`dahua_partly_overwritten.dd`)
Some footage is destroyed, so each camera comes back in **two pieces with a gap** between them:

{_seg_lines(r['dahua_partly_overwritten.dd'])}

Open **Cross-Camera Timeline**: you should see the gaps drawn as striped areas.

### Test 4: CP Plus (`cpplus_deleted.dd`)
Brand shown as **{r['cpplus_deleted.dd']['brand']}** (confidence {r['cpplus_deleted.dd']['confidence']}): the tool routes it through its Dahua engine and says it is **unverified**.

{_seg_lines(r['cpplus_deleted.dd'])}

### Test 5: TP-Link (`tplink_deleted.dd`)
Brand shown as **{r['tplink_deleted.dd']['brand']}**. No vendor parser exists, so the tool carves standard H.264 video only:

{_seg_lines(r['tplink_deleted.dd'])}

- Both cameras appear as **one** segment, with **no times**: the tool cannot tell cameras apart or read times without a vendor format.
  On the timeline it will be listed as "not positioned".
- This is the honest result for an unsupported brand. It is **not** a bug.

### Test 6: the stress image (`dahua_deleted_stress_tiny_clusters.dd`)
The recordings are chopped into 4 KiB pieces and interleaved, far smaller than any real disk, so keyframes (the big frames)
are spread over several pieces with the other camera's pieces in between. The tool now puts such frames back together when
the pieces are unambiguous: the scan note says "{stitched} frame(s) that straddled interleaved clusters were put back together".

{_seg_lines(r['dahua_deleted_stress_tiny_clusters.dd'])}

What is still lost: a frame whose 24-byte **header** is itself split across two pieces (the tool does not guess), and then every
frame that depends on it until the next keyframe. That is why this image does not reach 100%. Real disks use pieces of megabytes,
where this is rare.

## Face search (find a person across the recordings)

1. On **Recordings**, **export** both segments (press **Export all segments**). Face search only looks at exported videos, and checks them
   for you: there is no separate "Faces" step needed.
2. Under **Search for a Person Across Recordings**, choose `people/person_A.png` and press Search. The tool's match threshold is {thr}.
   The result is one line per camera: the best similarity and whether it is above or below the threshold.
   - Expected on `dahua_deleted.dd`: person A is **above** the threshold in the Camera 1 recording only (best similarity about {r['dahua_deleted.dd']['segments'][0]['best_similarity']['A']:.2f});
     the Camera 2 recording scores about {r['dahua_deleted.dd']['segments'][1]['best_similarity']['A']:.2f}, **below** the threshold, which is correct (A never appears there).
3. Search with `person_B.png`: B matches **both** recordings.
4. The two faces score about {sims['A-B']:.2f} against each other, so the model tells them apart easily.

Read this carefully: the people are simple avatars that render identically in every frame, which makes this an easy test. It shows the
search plumbing works. It says nothing about accuracy on real people, where lookalikes, angles, lighting and video quality all matter.
To test with real people (with their consent), rebuild the pack with `--photo-a` and `--photo-b`.

## Accuracy test (how much of the deleted video came back)

On **Recordings**, open **Accuracy Against Ground Truth** and supply:
- **Ground-truth video**: `truth_videos/camera1_persons_A_and_B.mp4`
- **Original disk image**: the full path of `disks/dahua_before_deletion.dd`
- Leave "Frame comparison" on **Exact**.

Expected for the deleted Dahua disk against the Camera 1 clip: **{acc['deleted_vs_camera1_clip']['frame_recall']}% of frames recovered**
({acc['deleted_vs_camera1_clip']['in_order']}% in the right order, byte recall {acc['deleted_vs_camera1_clip']['byte_recall']}%).
Against the Camera 2 clip: **{acc['deleted_vs_camera2_clip']['frame_recall']}%** (the report also lists the other camera's frames as "extra", which is why precision reads about {acc['deleted_vs_camera2_clip']['frame_precision']}%).

For the stress image against the Camera 1 clip the tool reports **{acc['stress_vs_camera1_clip']['frame_recall']}%**: the accuracy feature measures exactly
what the stitching could not save (see test 6). The same numbers come from the command line: `python -m backend.validation_kit --after disks/dahua_deleted.dd --before disks/dahua_before_deletion.dd --clip truth_videos/camera1_persons_A_and_B.mp4`.

## Cross-camera timeline

On the Dahua-style disks (tests 1, 3 and 4) the cameras overlap in time: Camera 1 starts at {t0} and Camera 2 three seconds later.
Open **Cross-Camera Timeline**: you should see two lanes, and the correlated-events card should list **one event** with both cameras
from {t0} to {t1}. On the partly overwritten disk the lanes also show the gaps (a few seconds each) as striped areas.
TP-Link has no times, so its single segment appears under "not positioned" and there is no correlated event.

## Other checks worth doing

- **Faces / Objects:** after exporting, the **Faces** button reports how many faces were seen in the sampled frames (up to 2 in the Camera 1 recording); **Objects** finds a "person" in the cartoon scene.
- **Motion:** press Motion on an exported segment. The people move, so motion should be detected.
- **Object detection:** do not expect much. The people are cartoons and the object model was trained on photographs.
- **Encrypted package:** on Report & Certificate, create a package with a 12+ character passphrase; then open it with
  `python -m backend.case_package decrypt file.sihpkg out.zip` and check the same files come out.
- **Tamper check:** change one byte of a copy of a disk (any hex editor), load it and press **Verify Image Hashes**: it must report a mismatch.
- **No-video file:** load any non-recorder file (a photo, a document). The scan should say **No video found** with a plain explanation.
- **Certificate details:** fill in the police station, FIR and so on, generate the PDF, and confirm they appear exactly as typed and are marked "as entered by the examiner".

## If something does not match

Note the disk file name, what the screen showed, and the tool's Hash Audit Log for that case, and send them to whoever maintains the tool.
The generator is `tools/make_test_pack.py`; running it again rebuilds the same pack (the videos differ by tiny encoder noise, the results should not).
"""
    (out / "START_HERE.md").write_text(text, encoding="utf-8")
    (out / "expected_results.json").write_text(json.dumps(r, indent=2, default=str), encoding="utf-8")
