"""
bundle_env.py — Build-time script to embed client-safe Supabase credentials
                into the PyInstaller frozen build.

Run BEFORE pyinstaller:

    python packaging/bundle_env.py

Reads from the repo's .env file (or environment variables):
  SUPABASE_URL      — your Supabase project URL  (safe to bundle; no privileged access)
  SUPABASE_ANON_KEY — your Supabase anon/public key (safe to bundle; protected by RLS)

These are the same credentials you would put in a React/Flutter frontend app —
they are designed to be client-facing. The Postgres password (DATABASE_URL) is
NOT read here and is NOT bundled into the installer.

Writes: backend/_bundled_config.py
  Imported by backend/main.py at startup when running inside a frozen (PyInstaller)
  build and the env vars are not already set.

Security notes:
  • SUPABASE_ANON_KEY is a JWT with audience "anon". Row Level Security (RLS)
    policies on your Supabase project control what this key can and cannot do.
  • The raw Postgres connection password (DATABASE_URL) is NEVER written here.
  • This file writes credentials to a .py inside the source tree — do not commit
    the generated backend/_bundled_config.py (it is in .gitignore).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / ".env"
OUT_FILE = REPO_ROOT / "backend" / "_bundled_config.py"


def _load_env_file(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    if not path.is_file():
        return result
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        result[k.strip()] = v.strip()
    return result


def main() -> None:
    env_file_vars = _load_env_file(ENV_FILE)

    # Env vars take precedence over .env file values
    def get(key: str) -> str:
        return os.environ.get(key, env_file_vars.get(key, "")).strip()

    supabase_url = get("SUPABASE_URL")
    anon_key = get("SUPABASE_ANON_KEY")

    # Detect accidental postgres password bundling
    database_url = get("DATABASE_URL")
    if database_url and not (supabase_url and anon_key):
        print(
            "\n[WARNING] DATABASE_URL is set but SUPABASE_URL / SUPABASE_ANON_KEY are not.\n"
            "          DATABASE_URL contains your Postgres password — it must NOT be bundled\n"
            "          into the installer. Set SUPABASE_URL and SUPABASE_ANON_KEY instead.\n"
            "          Get them from: Supabase Dashboard → Settings → API\n",
            file=sys.stderr,
        )
        sys.exit(1)

    if not supabase_url or not anon_key:
        print(
            "\n[ERROR] SUPABASE_URL and SUPABASE_ANON_KEY must be set to build the installer.\n"
            "        Get them from: Supabase Dashboard → Settings → API\n"
            "        Add them to .env:\n"
            "          SUPABASE_URL=https://<your-project-ref>.supabase.co\n"
            "          SUPABASE_ANON_KEY=eyJ...\n",
            file=sys.stderr,
        )
        sys.exit(1)

    # Validate URL looks like a Supabase project URL (not a postgres connection string)
    if not supabase_url.startswith("https://") or ".supabase.co" not in supabase_url:
        print(
            f"\n[ERROR] SUPABASE_URL does not look like a Supabase project URL: {supabase_url!r}\n"
            "        Expected format: https://<ref>.supabase.co\n",
            file=sys.stderr,
        )
        sys.exit(1)

    # Write the bundled config — simple Python module, no encryption needed because
    # these credentials are designed to be client-facing (anon key + URL, not password).
    OUT_FILE.write_text(
        f'"""Auto-generated by packaging/bundle_env.py — do not edit by hand."""\n'
        f"# These are client-safe Supabase credentials (anon key + project URL).\n"
        f"# Protected by Row Level Security (RLS) policies on the Supabase project.\n"
        f"SUPABASE_URL = {supabase_url!r}\n"
        f"SUPABASE_ANON_KEY = {anon_key!r}\n",
        encoding="utf-8",
    )

    print(f"[OK] Written: {OUT_FILE}")
    print(f"     SUPABASE_URL      = {supabase_url}")
    print(f"     SUPABASE_ANON_KEY = {anon_key[:12]}...{anon_key[-4:]} ({len(anon_key)} chars)")


if __name__ == "__main__":
    main()
