"""
bundle_env.py — Build-time configuration for PyInstaller frozen builds.
By default, produces a 100% offline local desktop application with no embedded credentials.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = REPO_ROOT / "backend" / "_bundled_config.py"


def main() -> None:
    # SIH Forensic Tool is 100% offline local desktop by default.
    OUT_FILE.write_text(
        '"""Auto-generated by packaging/bundle_env.py — do not edit by hand."""\n'
        '# Local offline desktop mode: no credentials bundled.\n'
        'SUPABASE_URL = None\n'
        'SUPABASE_ANON_KEY = None\n',
        encoding="utf-8",
    )
    print(f"[OK] Written offline configuration: {OUT_FILE}")


if __name__ == "__main__":
    main()
