"""
make_test_pack.py — build a folder of generated disk images, reference photos and ground-truth clips you can load into
the tool and check against KNOWN answers.

    python tools/make_test_pack.py "C:/path/to/sih-test-pack"            build + self-check
    python tools/make_test_pack.py OUT --photo-a me.jpg --photo-b friend.jpg   use your own (consented) photos
    python tools/make_test_pack.py OUT --quick                             tiny 4-second version (used by the tests)

HONEST LIMITS: everything here is generated by us. The people are cartoon avatars (or your own photos), the video is
rendered, and the recorder layouts are built from the public specifications the tool implements. Nothing here has been
written by a physical DVR/NVR, so it can show that the tool's plumbing works and that its results match what we put in;
it cannot show that a real recorder's disk will decode.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import struct
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).parent))

from testpack import personas  # noqa: E402

W, H, FPS = 640, 360, 10
BASE = datetime(2025, 5, 1, 9, 0, 0, tzinfo=timezone.utc)
BASE_TS = int(BASE.timestamp())


# ── the scene ──────────────────────────────────────────────────────────────────

def _background() -> np.ndarray:
    bg = np.zeros((H, W, 3), np.uint8)
    for y in range(H):
        v = 205 - int(35 * y / H)
        bg[y, :] = (v - 6, v, v + 4)
    cv2.rectangle(bg, (0, int(H * 0.82)), (W, H), (120, 125, 130), -1)             # floor
    cv2.rectangle(bg, (int(W * 0.06), int(H * 0.14)), (int(W * 0.2), int(H * 0.82)), (95, 110, 130), -1)   # door
    cv2.rectangle(bg, (int(W * 0.78), int(H * 0.2)), (int(W * 0.95), int(H * 0.45)), (170, 190, 205), -1)  # window
    return bg


def _paste(frame: np.ndarray, sprite: np.ndarray, alpha: np.ndarray, x: int, y: int) -> None:
    h, w = sprite.shape[:2]
    x0, y0, x1, y1 = max(x, 0), max(y, 0), min(x + w, W), min(y + h, H)
    if x0 >= x1 or y0 >= y1:
        return
    s = sprite[y0 - y:y1 - y, x0 - x:x1 - x]
    a = alpha[y0 - y:y1 - y, x0 - x:x1 - x][:, :, None]
    frame[y0:y1, x0:x1] = (frame[y0:y1, x0:x1] * (1 - a) + s * a).astype(np.uint8)


def _sprite(source: np.ndarray, size: int) -> tuple[np.ndarray, np.ndarray]:
    bg_colour = tuple(int(v) for v in source[4, 4])
    bgr, alpha = personas.cutout(source, bg_colour)
    return cv2.resize(bgr, (size, size), interpolation=cv2.INTER_AREA), cv2.resize(alpha, (size, size), interpolation=cv2.INTER_AREA)


def render(camera: int, people: list[dict], seconds: int, out_h264: Path, ffmpeg: str) -> None:
    """people: [{"portrait": bgr, "path": f(t)->(x_centre, y_bottom), "size": px}], drawn in list order."""
    sprites = [(_sprite(p["portrait"], p["size"]), p) for p in people]
    proc = subprocess.Popen(
        [ffmpeg, "-y", "-loglevel", "error", "-f", "rawvideo", "-pix_fmt", "bgr24", "-s", f"{W}x{H}", "-r", str(FPS), "-i", "-",
         "-c:v", "libx264", "-profile:v", "baseline", "-pix_fmt", "yuv420p", "-g", "25", "-bf", "0", "-crf", "27",
         "-f", "h264", str(out_h264)], stdin=subprocess.PIPE)
    bg = _background()
    rng = np.random.default_rng(camera)
    for n in range(seconds * FPS):
        t = n / FPS
        frame = bg.copy()
        for (bgr, alpha), p in sprites:
            pos = p["path"](t)
            if pos is not None:
                _paste(frame, bgr, alpha, int(pos[0] - p["size"] / 2), int(pos[1] - p["size"]))
        stamp = f"CAM {camera:02d}  2025-05-01 09:{int(t // 60):02d}:{int(t % 60):02d}"
        cv2.putText(frame, stamp, (12, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 2, cv2.LINE_AA)
        frame = np.clip(frame.astype(np.int16) + rng.normal(0, 2, frame.shape), 0, 255).astype(np.uint8)   # sensor noise
        proc.stdin.write(frame.tobytes())
    proc.stdin.close()
    if proc.wait() != 0:
        raise RuntimeError("ffmpeg failed while encoding the scene")


def _lerp(a, b, u):
    return a + (b - a) * min(1.0, max(0.0, u))


def make_paths(seconds: int):
    """Camera 1: A and B walk in, stand facing each other (both faces visible), then leave. Camera 2: B walks across."""
    s = seconds
    walk_in, stay_until = 0.25 * s, 0.75 * s

    def a_path(t):                       # from the left, stops, then leaves to the left again
        if t < walk_in:
            return (_lerp(-90, W * 0.34, t / walk_in), H - 8)
        if t < stay_until:
            return (W * 0.34 + 4 * math.sin(t * 2), H - 8)
        return (_lerp(W * 0.34, -110, (t - stay_until) / (s - stay_until)), H - 8)

    def b_path(t):                       # from the right, stops next to A, then leaves to the right
        if t < walk_in:
            return (_lerp(W + 90, W * 0.66, t / walk_in), H - 34)
        if t < stay_until:
            return (W * 0.66 + 4 * math.sin(t * 2 + 1), H - 34)
        return (_lerp(W * 0.66, W + 110, (t - stay_until) / (s - stay_until)), H - 34)

    def b_cross(t):                      # camera 2: left to right across the whole scene
        return (_lerp(-90, W + 90, t / s), H - 20)

    return a_path, b_path, b_cross


# ── recorder images (built with the same helpers the tests use, with a bigger disk) ─────────────────────────────

CLUSTER_SECTORS = 128         # 64 KiB clusters (real Dahua disks use far larger ones); a smaller size is used for the stress image
STRESS_CLUSTER_SECTORS = 8    # 4 KiB clusters: nearly every frame straddles an interleaved cluster boundary


def _dhfs_module(n_clusters: int, sectors_per_cluster: int = CLUSTER_SECTORS):
    from backend.tests import test_dahua_dhfs as D
    from backend.plugins.constants import DHFS_DESC_SIZE
    D._SPC = sectors_per_cluster
    D._CL = sectors_per_cluster * 512
    D._N_DESC = n_clusters
    D._VIDEO_SECTOR = D._DESC_SECTOR + math.ceil(n_clusters * DHFS_DESC_SIZE / 512) + 8
    D._EXT = bytes([0x80, 0x00, W // 8, H // 8, 0x81, 0x00, 0x08, FPS])
    return D


def build_dahua(cam1: bytes, cam2: bytes, sectors_per_cluster: int = CLUSTER_SECTORS):
    """(intact_disk, deleted_disk, partly_overwritten_disk, layout notes)."""
    cl_bytes = sectors_per_cluster * 512
    n_clusters = 2 * (math.ceil(len(cam1) / cl_bytes) + 4) + 2 * (math.ceil(len(cam2) / cl_bytes) + 4) + 40
    D = _dhfs_module(n_clusters, sectors_per_cluster)
    cl = D._CL
    d1 = D._dhav_stream(cam1, 0, BASE_TS)
    d2 = D._dhav_stream(cam2, 1, BASE_TS + 3)
    na, nb = -(-len(d1) // cl), -(-len(d2) // cl)
    ca = [2 * i + 2 for i in range(na)]                                  # camera 1 on even clusters ...
    cb = [2 * i + 3 for i in range(nb)]                                  # ... camera 2 on odd ones (interleaved, fragmented)
    assert max(ca + cb) < n_clusters - 5
    intact = D.build_dhfs_disk([dict(camera=1, data=d1, clusters=ca, t0=0), dict(camera=2, data=d2, clusters=cb, t0=3)])

    from backend.plugins.constants import DHFS_DESC_SIZE
    wiped = bytearray(intact)
    dt = D._DESC_SECTOR * 512
    for i in range(D._N_DESC):                                           # deletion as a recorder's menu might do it
        wiped[dt + i * DHFS_DESC_SIZE: dt + (i + 1) * DHFS_DESC_SIZE] = b"\xfe" + b"\x00" * (DHFS_DESC_SIZE - 1)

    part = bytearray(wiped)                                              # ... and new recordings overwrote part of it
    va = D._VIDEO_SECTOR * 512
    rng = np.random.default_rng(7)

    def overwrite(clusters, data_len, lo_frac, hi_frac):
        """Overwrite bytes lo..hi (as fractions of one camera's data) wherever they landed on the disk."""
        lo, hi = int(lo_frac * data_len), int(hi_frac * data_len)
        for n, idx in enumerate(clusters):
            a, b = max(lo, n * cl), min(hi, (n + 1) * cl)
            if a < b:
                start = va + idx * cl + (a - n * cl)
                part[start:start + (b - a)] = rng.integers(0, 256, b - a, dtype=np.uint8).tobytes()

    overwrite(ca, len(d1), 0.35, 0.55)                                   # camera 1: a stretch in the middle is gone
    overwrite(cb, len(d2), 0.60, 0.75)                                   # camera 2: a stretch nearer the end is gone
    return bytes(intact), bytes(wiped), bytes(part), dict(dahua_streams=(d1, d2), clusters=(na, nb))


def build_cpplus(cam1: bytes, cam2: bytes, D) -> bytes:
    """CP Plus: banner + noise + Dahua-style DHAV streams (assumed Dahua-compatible; NOT verified on a real CP Plus disk)."""
    rng = np.random.default_rng(11)
    noise = lambda n: rng.integers(0, 256, n, dtype=np.uint8).tobytes()         # noqa: E731
    return (b"CP PLUS DVR SYSTEM - ADITYA INFOTECH LTD\x00\x00\x00" + noise(1024) +
            D._dhav_stream(cam1, 0, BASE_TS) + noise(6000) + D._dhav_stream(cam2, 1, BASE_TS + 3) + noise(4096))


def build_tplink(cam1: bytes, cam2: bytes) -> bytes:
    """TP-Link: vendor text + noise + plain H.264 streams. The tool has no TP-Link parser, so only generic carving applies."""
    rng = np.random.default_rng(13)
    noise = lambda n: rng.integers(0, 256, n, dtype=np.uint8).tobytes()         # noqa: E731
    return b"TP-LINK VIGI NVR\x00" + noise(2048) + cam1 + noise(9000) + cam2 + noise(4096)


# ── pack assembly ──────────────────────────────────────────────────────────────

def _ffmpeg() -> str:
    exe = shutil.which("ffmpeg")
    if not exe or not shutil.which("ffprobe"):
        raise SystemExit("ffmpeg and ffprobe must be on PATH (see the project README).")
    return exe


def _to_mp4(h264: Path, mp4: Path, ffmpeg: str) -> None:
    subprocess.run([ffmpeg, "-y", "-loglevel", "error", "-f", "h264", "-r", str(FPS), "-i", str(h264), "-c", "copy", str(mp4)], check=True)


def _person_image(name: str, photo: str | None) -> np.ndarray:
    if photo:
        img = cv2.imread(photo)
        if img is None:
            raise SystemExit(f"Could not read the photo: {photo}")
        side = min(img.shape[:2])
        y, x = (img.shape[0] - side) // 2, (img.shape[1] - side) // 2
        return cv2.resize(img[y:y + side, x:x + side], (300, 300), interpolation=cv2.INTER_AREA)
    return personas.person_portrait(name)


def _check_people(people: dict) -> dict:
    """Prove with the tool's own face models that each person is found and the people are told apart."""
    from backend import face_search
    embs = {}
    for name, img in people.items():
        ok, buf = cv2.imencode(".png", img)
        emb = face_search.extract_embedding_from_image_bytes(buf.tobytes())
        if emb is None:
            raise SystemExit(f"The tool's face detector finds no face in the reference image for person {name}. "
                             f"If you used your own photo, use a clear, front-facing one.")
        embs[name] = emb
    sims = {}
    names = sorted(embs)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            sims[f"{a}-{b}"] = face_search.cosine_similarity(embs[a], embs[b])
            if sims[f"{a}-{b}"] >= face_search.REFERENCE_MATCH_THRESHOLD:
                raise SystemExit(f"People {a} and {b} look too alike to the face model "
                                 f"({sims[f'{a}-{b}']:.2f} >= {face_search.REFERENCE_MATCH_THRESHOLD}); use different photos.")
    return sims


def build(out: Path, seconds: int, photo_a: str | None, photo_b: str | None, verify_pack: bool = True) -> dict:
    ffmpeg = _ffmpeg()
    for sub in ("people", "truth_videos", "disks", "_work"):
        (out / sub).mkdir(parents=True, exist_ok=True)
    work = out / "_work"

    people = {"A": _person_image("A", photo_a), "B": _person_image("B", photo_b)}
    sims = _check_people(people)
    for name, img in people.items():
        cv2.imwrite(str(out / "people" / f"person_{name}.png"), img)

    a_path, b_path, b_cross = make_paths(seconds)
    size = 210
    render(1, [dict(portrait=people["A"], path=a_path, size=size), dict(portrait=people["B"], path=b_path, size=size - 40)],
           seconds, work / "cam1.h264", ffmpeg)
    render(2, [dict(portrait=people["B"], path=b_cross, size=size - 20)], seconds, work / "cam2.h264", ffmpeg)
    cam1, cam2 = (work / "cam1.h264").read_bytes(), (work / "cam2.h264").read_bytes()
    _to_mp4(work / "cam1.h264", out / "truth_videos" / "camera1_persons_A_and_B.mp4", ffmpeg)
    _to_mp4(work / "cam2.h264", out / "truth_videos" / "camera2_person_B_only.mp4", ffmpeg)

    intact, wiped, partial, _ = build_dahua(cam1, cam2)
    _, stress, _, _ = build_dahua(cam1, cam2, STRESS_CLUSTER_SECTORS)
    D = _dhfs_module(600)
    disks = out / "disks"
    files = {
        "dahua_before_deletion.dd": intact,
        "dahua_deleted.dd": wiped,
        "dahua_partly_overwritten.dd": partial,
        "dahua_deleted_stress_tiny_clusters.dd": stress,
        "cpplus_deleted.dd": build_cpplus(cam1, cam2, D),
        "tplink_deleted.dd": build_tplink(cam1, cam2),
    }
    for name, data in files.items():
        (disks / name).write_bytes(data)
    shutil.rmtree(work, ignore_errors=True)
    info = {"similarities": sims, "sizes": {k: len(v) for k, v in files.items()}, "seconds": seconds}
    if verify_pack:
        from testpack import guide, verify
        print("Running the tool over the pack to record what it really finds (about a minute)...", file=sys.stderr)
        observed = verify.verify(out)
        guide.write(out, observed, seconds, sims, own_photos=bool(photo_a or photo_b))
        info["observed"] = {k: v for k, v in observed.items() if not k.startswith("_")}
    return info


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("out", help="folder to create the pack in")
    ap.add_argument("--seconds", type=int, default=12, help="length of each camera's video (default 12)")
    ap.add_argument("--quick", action="store_true", help="4-second videos, for the automated tests")
    ap.add_argument("--no-verify", action="store_true", help="skip running the tool over the pack (no START_HERE.md is written)")
    ap.add_argument("--photo-a", help="use your own photo for person A (consent required)")
    ap.add_argument("--photo-b", help="use your own photo for person B (consent required)")
    args = ap.parse_args()
    seconds = 4 if args.quick else args.seconds
    info = build(Path(args.out), seconds, args.photo_a, args.photo_b, verify_pack=not args.no_verify)
    info.pop("observed", None)
    print(json.dumps(info, indent=2))


if __name__ == "__main__":
    main()
